<?php
header("content-type:image/png");
srand((double)microtime()*1000000);//播下一个生成随机数字的种子，以方便下面随机数生成的使用
session_start();//将随机数存入session中
$_SESSION['code']="";
$img=ImageCreate(60,18);
$bgcolor=ImageColorAllocate($img,0,0,0);
$red=ImageColorAllocate($img,255,0,0);
$bgcolortrans=ImageColorTransparent($img,$bgcolor);
while(($code=rand()%10000)<1000);//设置位数
$_SESSION['code']=$code; 
ImageString($img,5,10,1,$code,$red);
ImagePng($img);
ImageDestroy($img);
?>